# Generated by Django 4.2.3 on 2023-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoosterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('meta_value', models.TextField()),
            ],
        ),
    ]
